//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    public partial class BookCatalog
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// pnlUserHeader control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlUserHeader;

        /// <summary>
        /// lblUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUserName;

        /// <summary>
        /// btnLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLogout;

        /// <summary>
        /// pnlGuestHeader control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlGuestHeader;

        /// <summary>
        /// lnkMyBooks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkMyBooks;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// btnShowAll control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnShowAll;

        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// gvBooks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvBooks;
    }
}