//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{


    public partial class Borrowings
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.ValidationSummary valSummaryBorrow;
        protected global::System.Web.UI.WebControls.DropDownList ddlMember;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator reqMember;
        protected global::System.Web.UI.WebControls.DropDownList ddlBook;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator reqBook;
        protected global::System.Web.UI.WebControls.TextBox txtBorrowDate;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator reqBorrowDate;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator regexBorrowDate;
        protected global::System.Web.UI.WebControls.TextBox txtDueDate;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator regexDueDate;
        protected global::System.Web.UI.WebControls.Button btnBorrow;
        protected global::System.Web.UI.WebControls.Label lblBorrowMessage;
        protected global::System.Web.UI.WebControls.GridView gvActive;
    }
}
