//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    public partial class UserBorrowings
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUserName;

        /// <summary>
        /// btnProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnProfile;

        /// <summary>
        /// btnLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLogout;

        /// <summary>
        /// lblActiveBorrowings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblActiveBorrowings;

        /// <summary>
        /// lblTotalBorrowings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalBorrowings;

        /// <summary>
        /// lblOverdueBooks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOverdueBooks;

        /// <summary>
        /// pnlActiveBorrowings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlActiveBorrowings;

        /// <summary>
        /// gvActiveBorrowings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvActiveBorrowings;

        /// <summary>
        /// pnlBorrowingHistory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlBorrowingHistory;

        /// <summary>
        /// gvBorrowingHistory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvBorrowingHistory;
    }
}